dbt_elsa:
  target: dev_live
  outputs:
    dev_live:
      type: postgres
      threads: 16
      host: db_airflow
      port: 5432
      user: airflow
      password: airflow        
      dbname: airflow
      schema: bronze           # ➜ schema par défaut, tu peux l’écraser dans dbt_project.yml

  